services:
  - type: web
    name: concours-facile-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
        